add sci-m docs
Green-Software-Foundation/ief pull request #198
Opened 2023-10-12 10:14 UTC by jmcook1186

### Types of changes

- [x] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

Updates the docs for sci-m and adds an example `impl` file that runs `sci-m` in isolation.

2023-10-12 11:14 UTC, narekhovhannisyan commented on examples/impls/sci-m.yml
> +          duration: 3600
newline at the end of file

2023-10-12 11:16 UTC, narekhovhannisyan commented
@jmcook1186 for commit messages to be according to our contribution document, you can use following pattern

```
scope: change which is done.

// f. ex. for current changes
docs: add `sci-m` documentation.
```

2023-10-13 08:28 UTC, jmcook1186 commented on examples/impls/sci-m.yml
> +          duration: 3600
```suggestion
          duration: 3600

```

2023-10-13 09:40 UTC, gnanakeethan requested changes

2023-10-13 09:40 UTC, gnanakeethan commented on examples/impls/sci-m.yml
> +          el: 3 # 3 years in seconds
```suggestion
          el: 94608000 # 3 years in seconds        
```

2023-10-13 09:40 UTC, gnanakeethan commented on examples/impls/sci-m.yml
> +          tir: 1 # s per hour
```suggestion
          tir: 3600 # 1hr in seconds
```

2023-10-17 09:08 UTC, gnanakeethan approved these changes

2023-10-17 09:08 UTC, merged